"""build.py -- Vivado synthesis, implementation, and bitstream generation.

Reads project.toml and per-module manifests, generates TCL on the fly
for Vivado non-project mode.

Usage:
    python scripts/build.py synth|impl|bit [--gui]
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import (
    find_project_root,
    load_config,
    collect_rtl_sources,
    collect_constraints,
    require_tool,
    run,
)


def tcl_path(p: Path) -> str:
    """Convert a Path to a forward-slash string for TCL."""
    return str(p.resolve()).replace("\\", "/")


def generate_tcl(cfg: dict, root: Path, build_dir: Path, stage: str) -> Path:
    """Generate a Vivado TCL script for the requested build stage.

    Stages are cumulative: synth < impl < bit.
    Returns the path to the generated .tcl file.
    """
    project_name = cfg["project"]["name"]
    top = cfg["project"]["top"]
    part = cfg["project"]["part"]

    sources, inc_dirs = collect_rtl_sources(root, cfg)
    constraints = collect_constraints(root, cfg)

    lines = [
        "# Auto-generated by build.py -- do not edit",
        f'set project_name "{project_name}"',
        f'set top_module   "{top}"',
        f'set part         "{part}"',
        f'set build_dir    "{tcl_path(build_dir)}"',
        "",
        "# Create in-memory project (non-project mode)",
        "create_project -in_memory -part $part",
        "",
    ]

    # Read sources
    for src in sources:
        ext = src.suffix.lower()
        if ext == ".sv":
            lines.append(f'read_verilog -sv "{tcl_path(src)}"')
        elif ext == ".v":
            lines.append(f'read_verilog "{tcl_path(src)}"')
        elif ext in (".vhd", ".vhdl"):
            lines.append(f'read_vhdl "{tcl_path(src)}"')
    lines.append("")

    # Include directories
    if inc_dirs:
        inc_str = " ".join(f'"{tcl_path(d)}"' for d in inc_dirs)
        lines.append(f"set_property include_dirs [list {inc_str}] [current_fileset]")
    lines.append("")

    # Read constraints
    for xdc in constraints:
        lines.append(f'read_xdc "{tcl_path(xdc)}"')
    lines.append("")

    # Synthesis
    lines += [
        "# Synthesis",
        "synth_design -top $top_module -part $part",
        'write_checkpoint -force "$build_dir/post_synth.dcp"',
        'report_timing_summary -file "$build_dir/timing_synth.rpt"',
        'report_utilization -file "$build_dir/utilization_synth.rpt"',
    ]

    # Implementation
    if stage in ("impl", "bit"):
        lines += [
            "",
            "# Implementation",
            "opt_design",
            "place_design",
            "phys_opt_design",
            "route_design",
            'write_checkpoint -force "$build_dir/post_route.dcp"',
            'report_timing_summary -file "$build_dir/timing_route.rpt"',
            'report_utilization -file "$build_dir/utilization_route.rpt"',
        ]

    # Bitstream
    if stage == "bit":
        lines += [
            "",
            "# Bitstream",
            'write_bitstream -force "$build_dir/${project_name}.bit"',
        ]

    lines += ["", "exit"]

    tcl_file = build_dir / f"{stage}.tcl"
    tcl_file.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated TCL: {tcl_file}")
    return tcl_file


def main():
    parser = argparse.ArgumentParser(description="Vivado build script")
    parser.add_argument(
        "stage",
        choices=["synth", "impl", "bit"],
        help="Build stage to run",
    )
    parser.add_argument(
        "--gui",
        action="store_true",
        help="Open Vivado in GUI mode instead of batch",
    )
    args = parser.parse_args()

    root = find_project_root()
    cfg = load_config(root)

    vivado = require_tool("vivado", hint="Ensure Xilinx Vivado is on your PATH.")

    build_dir = root / cfg["impl"].get("build_dir", "impl")
    build_dir.mkdir(parents=True, exist_ok=True)

    tcl_file = generate_tcl(cfg, root, build_dir, args.stage)

    mode = "gui" if args.gui else "batch"
    run(
        [str(vivado), "-mode", mode, "-source", str(tcl_file), "-nojournal", "-nolog"],
        cwd=build_dir,
    )


if __name__ == "__main__":
    main()
